// 60 Vocabulary Topics and CEFR Difficulty Levels Definition
// Fully synchronized with titles and introductory text from Document 1 (3000 từ vựng Tiếng Anh theo chủ đề)

export const TOPICS = [
  {
    id: 'school_supplies',
    name: 'Đồ dùng học tập',
    nameVi: 'Đồ dùng học tập',
    enName: 'School Supplies',
    nameEn: 'School-supplies',
    title: 'School-supplies (Đồ dùng học tập)',
    introText: 'Từ vựng thuộc chủ đề đồ dùng học tập gồm 65 từ cơ bản:',
    icon: '🎒',
    color: 'indigo',
    wordCount: 65,
  },
  {
    id: 'actions',
    name: 'Hành động',
    nameVi: 'Hành động',
    enName: 'Actions',
    nameEn: 'Actions',
    title: 'Actions (Hành động)',
    introText: 'Từ vựng chủ đề hành động bao gồm 40 từ vựng như sau:',
    icon: '🏃',
    color: 'emerald',
    wordCount: 40,
  },
  {
    id: 'everyday_activities',
    name: 'Hoạt động thường ngày',
    nameVi: 'Hoạt động thường ngày',
    enName: 'Everyday Activities',
    nameEn: 'Everyday activities',
    title: 'Everyday activities (Hoạt động thường ngày)',
    introText: 'Có 49 từ vựng cơ bản thuộc nhóm từ vựng với chủ đề hoạt động thường ngày.',
    icon: '☕',
    color: 'amber',
    wordCount: 49,
  },
  {
    id: 'sea',
    name: 'Biển',
    nameVi: 'Biển',
    enName: 'Sea',
    nameEn: 'Sea',
    title: 'Sea (Biển)',
    introText: 'Từ vựng Tiếng Anh chủ đề về biển có 33 từ vựng cực hay.',
    icon: '🌊',
    color: 'cyan',
    wordCount: 33,
  },
  {
    id: 'numbers',
    name: 'Số đếm',
    nameVi: 'Số đếm',
    enName: 'The number',
    nameEn: 'The number',
    title: 'The number (Số đếm)',
    introText: 'Xem ngay 20 từ vựng cơ bản liên quan đến chủ đề số đếm tại đây.',
    icon: '🔢',
    color: 'blue',
    wordCount: 20,
  },
  {
    id: 'shopping',
    name: 'Mua sắm',
    nameVi: 'Mua sắm',
    enName: 'Shopping',
    nameEn: 'Shopping',
    title: 'Shopping (Mua sắm)',
    introText: 'Tìm hiểu 42 từ vựng cơ bản nói về chủ đề mua sắm.',
    icon: '🛍️',
    color: 'pink',
    wordCount: 42,
  },
  {
    id: 'bedroom',
    name: 'Phòng ngủ',
    nameVi: 'Phòng ngủ',
    enName: 'Bedroom',
    nameEn: 'Bedroom',
    title: 'Bedroom (Phòng ngủ)',
    introText: 'Với chủ đề phòng ngủ, bạn có 26 từ vựng cơ bản cần biết đó là:',
    icon: '🛏️',
    color: 'purple',
    wordCount: 26,
  },
  {
    id: 'friendship',
    name: 'Tình bạn',
    nameVi: 'Tình bạn',
    enName: 'Friendship',
    nameEn: 'Friendship',
    title: 'Friendship (Tình bạn)',
    introText: 'Chủ đề về tình bạn có đến 17 từ vựng sau:',
    icon: '🤝',
    color: 'rose',
    wordCount: 17,
  },
  {
    id: 'kitchen',
    name: 'Các vật dụng trong nhà bếp',
    nameVi: 'Các vật dụng trong nhà bếp',
    enName: 'Kitchen',
    nameEn: 'Kitchen',
    title: 'Kitchen (Các vật dụng trong nhà bếp)',
    introText: 'Chủ đề về các vật dụng nhà bếp có tới 37 từ vựng.',
    icon: '🍳',
    color: 'orange',
    wordCount: 37,
  },
  {
    id: 'jewelry',
    name: 'Đồ trang sức',
    nameVi: 'Đồ trang sức',
    enName: 'Jewelry',
    nameEn: 'Jewelry',
    title: 'Jewelry (Đồ trang sức)',
    introText: 'Các món đồ trang sức được miêu tả với 20 từ vựng cơ bản.',
    icon: '💍',
    color: 'yellow',
    wordCount: 20,
  },
  {
    id: 'environment',
    name: 'Môi trường',
    nameVi: 'Môi trường',
    enName: 'Environment',
    nameEn: 'Environment',
    title: 'Environment (Môi trường)',
    introText: 'Từ vựng thuộc chủ đề môi trường gồm 20 từ cơ bản:',
    icon: '🌱',
    color: 'emerald',
    wordCount: 20,
  },
  {
    id: 'living_room',
    name: 'Phòng khách',
    nameVi: 'Phòng khách',
    enName: 'Living room',
    nameEn: 'Living room',
    title: 'Living room (Phòng khách)',
    introText: 'Chủ đề phòng khách có 32 từ vựng liên quan.',
    icon: '🛋️',
    color: 'teal',
    wordCount: 32,
  },
  {
    id: 'hospital',
    name: 'Bệnh viện',
    nameVi: 'Bệnh viện',
    enName: 'Hospital',
    nameEn: 'Hospital',
    title: 'Hospital (Bệnh viện)',
    introText: 'Nhóm 30 từ vựng cơ bản về chủ đề bệnh viện.',
    icon: '🏥',
    color: 'red',
    wordCount: 30,
  },
  {
    id: 'computer',
    name: 'Máy tính',
    nameVi: 'Máy tính',
    enName: 'Computer',
    nameEn: 'Computer',
    title: 'Computer (Máy tính)',
    introText: 'Chủ đề máy tính bao gồm 37 từ vựng cơ bản.',
    icon: '💻',
    color: 'sky',
    wordCount: 37,
  },
  {
    id: 'housework',
    name: 'Công việc nhà',
    nameVi: 'Công việc nhà',
    enName: 'Housework',
    nameEn: 'Housework',
    title: 'Housework (Công việc nhà)',
    introText: '20 từ vựng cơ bản về công việc nhà.',
    icon: '🧹',
    color: 'amber',
    wordCount: 20,
  },
  {
    id: 'shops',
    name: 'Các cửa hàng',
    nameVi: 'Các cửa hàng',
    enName: 'The shops',
    nameEn: 'The shops',
    title: 'The shops (Các cửa hàng)',
    introText: 'Có 18 từ vựng cơ bản thuộc nhóm từ vựng với chủ đề các cửa hàng.',
    icon: '🏪',
    color: 'indigo',
    wordCount: 18,
  },
  {
    id: 'entertainment',
    name: 'Giải trí',
    nameVi: 'Giải trí',
    enName: 'Entertainment',
    nameEn: 'Entertaiment',
    title: 'Entertaiment (Giải trí)',
    introText: 'Xem ngay 20 từ vựng cơ bản liên quan đến chủ đề giải trí sau:',
    icon: '🎭',
    color: 'purple',
    wordCount: 20,
  },
  {
    id: 'traveling',
    name: 'Du lịch',
    nameVi: 'Du lịch',
    enName: 'Traveling',
    nameEn: 'Traveling',
    title: 'Traveling (Du lịch)',
    introText: 'Từ vựng Tiếng Anh chủ đề về du lịch có 21 từ vựng cực hay.',
    icon: '✈️',
    color: 'blue',
    wordCount: 21,
  },
  {
    id: 'hometown',
    name: 'Quê hương',
    nameVi: 'Quê hương',
    enName: 'Hometown',
    nameEn: 'Hometown',
    title: 'Hometown (Quê hương)',
    introText: 'Với chủ đề quê hương, bạn có 35 từ vựng cơ bản cần biết đó là:',
    icon: '🏡',
    color: 'green',
    wordCount: 35,
  },
  {
    id: 'mid_autumn',
    name: 'Tết Trung thu',
    nameVi: 'Tết Trung thu',
    enName: 'Mid-Autumn',
    nameEn: 'Mid-Autumn',
    title: 'Mid-Autumn (Tết trung thu)',
    introText: 'Có 12 từ vựng cơ bản thuộc nhóm từ vựng với chủ đề tết trung thu.',
    icon: '🥮',
    color: 'yellow',
    wordCount: 12,
  },
  {
    id: 'wedding',
    name: 'Đám cưới',
    nameVi: 'Đám cưới',
    enName: 'Wedding',
    nameEn: 'Wedding',
    title: 'Wedding (Đám cưới)',
    introText: 'Chủ đề về đám cưới được miêu tả với 31 từ vựng cơ bản sau.',
    icon: '💒',
    color: 'rose',
    wordCount: 31,
  },
  {
    id: 'airport',
    name: 'Sân bay',
    nameVi: 'Sân bay',
    enName: 'Airport',
    nameEn: 'Airport',
    title: 'Airport (Sân bay)',
    introText: 'Có 16 từ vựng cơ bản thuộc chủ đề sân bay.',
    icon: '🛫',
    color: 'sky',
    wordCount: 16,
  },
  {
    id: 'health',
    name: 'Sức khỏe',
    nameVi: 'Sức khỏe',
    enName: 'Health',
    nameEn: 'Health',
    title: 'Health (Sức khỏe)',
    introText: 'Chủ đề về sức khỏe gồm 55 từ vựng bên dưới:',
    icon: '🩺',
    color: 'red',
    wordCount: 55,
  },
  {
    id: 'vegetables',
    name: 'Rau củ quả',
    nameVi: 'Rau củ quả',
    enName: 'Vegetable',
    nameEn: 'Vegetable',
    title: 'Vegetable (Rau củ quả)',
    introText: 'Khám phá chủ đề về rau củ quả với 27 từ vựng cơ bản.',
    icon: '🥦',
    color: 'green',
    wordCount: 27,
  },
  {
    id: 'transport',
    name: 'Phương tiện giao thông',
    nameVi: 'Phương tiện giao thông',
    enName: 'Transport',
    nameEn: 'Transport',
    title: 'Transport (Phương tiện giao thông)',
    introText: 'Tìm hiểu 50 từ vựng cơ bản nói về chủ đề phương tiện giao thông.',
    icon: '🚗',
    color: 'orange',
    wordCount: 50,
  },
  {
    id: 'time',
    name: 'Thời gian',
    nameVi: 'Thời gian',
    enName: 'Time',
    nameEn: 'Time',
    title: 'Time (Thời gian)',
    introText: 'Bao gồm: 16 từ vựng cơ bản về thời gian, bạn có thể tham khảo tại đây.',
    icon: '⏰',
    color: 'violet',
    wordCount: 16,
  },
  {
    id: 'emotions',
    name: 'Cảm xúc',
    nameVi: 'Cảm xúc',
    enName: 'Emotions',
    nameEn: 'Emotions',
    title: 'Emotions (Cảm xúc)',
    introText: 'Chủ đề về cảm xúc có tới 21 từ vựng cơ bản.',
    icon: '😊',
    color: 'pink',
    wordCount: 21,
  },
  {
    id: 'character',
    name: 'Tính cách',
    nameVi: 'Tính cách',
    enName: 'Character',
    nameEn: 'Character',
    title: 'Character (Tính cách)',
    introText: 'Chủ đề về tính cách có tới 39 từ vựng.',
    icon: '🧠',
    color: 'indigo',
    wordCount: 39,
  },
  {
    id: 'drinks',
    name: 'Đồ uống',
    nameVi: 'Đồ uống',
    enName: 'Drinks',
    nameEn: 'Drinks',
    title: 'Drinks (Đồ uống)',
    introText: 'Có 20 từ vựng cơ bản về đồ uống.',
    icon: '🍹',
    color: 'amber',
    wordCount: 20,
  },
  {
    id: 'flowers',
    name: 'Các loài hoa',
    nameVi: 'Các loài hoa',
    enName: 'Flowers',
    nameEn: 'Flowers',
    title: 'Flowers (Các loài hoa)',
    introText: 'Bao gồm: 20 từ vựng cơ bản về các loài hoa, bạn có thể tham khảo tại đây.',
    icon: '🌸',
    color: 'rose',
    wordCount: 20,
  },
  {
    id: 'movies',
    name: 'Phim ảnh',
    nameVi: 'Phim ảnh',
    enName: 'Movies',
    nameEn: 'Movies',
    title: 'Movies (Phim ảnh)',
    introText: 'Có 21 từ vựng cơ bản về chủ đề phim ảnh.',
    icon: '🎬',
    color: 'purple',
    wordCount: 21,
  },
  {
    id: 'soccer',
    name: 'Bóng đá',
    nameVi: 'Bóng đá',
    enName: 'Soccer',
    nameEn: 'Soccer',
    title: 'Soccer (Bóng đá)',
    introText: 'Có 39 từ vựng cơ bản về chủ đề bóng đá.',
    icon: '⚽',
    color: 'emerald',
    wordCount: 39,
  },
  {
    id: 'christmas',
    name: 'Giáng sinh',
    nameVi: 'Giáng sinh',
    enName: 'Christmas',
    nameEn: 'Christmas',
    title: 'Christmas (Giáng sinh)',
    introText: 'Có 18 từ vựng cơ bản xoay quanh chủ đề về giáng sinh.',
    icon: '🎄',
    color: 'red',
    wordCount: 18,
  },
  {
    id: 'foods',
    name: 'Đồ ăn',
    nameVi: 'Đồ ăn',
    enName: 'Foods',
    nameEn: 'Foods',
    title: 'Foods (Đồ ăn)',
    introText: 'Chủ đề về đồ ăn phong phú với hơn 40 từ vựng cơ bản.',
    icon: '🍲',
    color: 'orange',
    wordCount: 40,
  },
  {
    id: 'sports',
    name: 'Thể thao',
    nameVi: 'Thể thao',
    enName: 'Sport',
    nameEn: 'Sport',
    title: 'Sport (Thể thao)',
    introText: 'Chủ đề thể thao có tới 36 từ vựng.',
    icon: '🏆',
    color: 'blue',
    wordCount: 36,
  },
  {
    id: 'music',
    name: 'Âm nhạc',
    nameVi: 'Âm nhạc',
    enName: 'Music',
    nameEn: 'Music',
    title: 'Music (Âm nhạc)',
    introText: 'Có 39 từ vựng cơ bản về chủ đề âm nhạc.',
    icon: '🎵',
    color: 'violet',
    wordCount: 39,
  },
  {
    id: 'love',
    name: 'Tình yêu',
    nameVi: 'Tình yêu',
    enName: 'Love',
    nameEn: 'Love',
    title: 'Love (Tình yêu)',
    introText: 'Có 19 từ vựng về chủ đề tình yêu.',
    icon: '💖',
    color: 'pink',
    wordCount: 19,
  },
  {
    id: 'restaurant_hotel',
    name: 'Nhà hàng- khách sạn',
    nameVi: 'Nhà hàng- khách sạn',
    enName: 'Restaurant - Hotel',
    nameEn: 'Restaurant - Hotel',
    title: 'Restaurant - Hotel (Nhà hàng- khách sạn)',
    introText: 'Có 37 từ vựng cơ bản về nhà hàng- khách sạn.',
    icon: '🍽️',
    color: 'amber',
    wordCount: 37,
  },
  {
    id: 'school',
    name: 'Trường học',
    nameVi: 'Trường học',
    enName: 'School',
    nameEn: 'School',
    title: 'School (Trường học)',
    introText: 'Có 38 từ vựng cơ bản về trường học.',
    icon: '🏫',
    color: 'cyan',
    wordCount: 38,
  },
  {
    id: 'colors',
    name: 'Màu sắc',
    nameVi: 'Màu sắc',
    enName: 'Colors',
    nameEn: 'Colors',
    title: 'Colors (Màu sắc)',
    introText: 'Có 20 từ vựng cơ bản về màu sắc.',
    icon: '🎨',
    color: 'indigo',
    wordCount: 20,
  },
  {
    id: 'weather',
    name: 'Thời tiết',
    nameVi: 'Thời tiết',
    enName: 'Weather',
    nameEn: 'Weather',
    title: 'Weather (Thời tiết)',
    introText: 'Chủ đề về thời tiết có 39 từ vựng sau:',
    icon: '☀️',
    color: 'yellow',
    wordCount: 39,
  },
  {
    id: 'clothes',
    name: 'Quần áo',
    nameVi: 'Quần áo',
    enName: 'Clothes',
    nameEn: 'Clothes',
    title: 'Clothes (Quần áo)',
    introText: 'Tìm hiểu 38 từ vựng cơ bản nói về chủ đề quần áo ngay!',
    icon: '👗',
    color: 'pink',
    wordCount: 38,
  },
  {
    id: 'body_parts',
    name: 'Bộ phận cơ thể',
    nameVi: 'Bộ phận cơ thể',
    enName: 'Body parts',
    nameEn: 'Body parts',
    title: 'Body parts (Bộ phận cơ thể)',
    introText: 'Có 26 từ vựng cơ bản về bộ phận cơ thể.',
    icon: '🧍',
    color: 'orange',
    wordCount: 26,
  },
  {
    id: 'education',
    name: 'Giáo dục',
    nameVi: 'Giáo dục',
    enName: 'Education',
    nameEn: 'Education',
    title: 'Education (Giáo dục)',
    introText: 'Có 55 từ vựng cơ bản thuộc chủ đề giáo dục.',
    icon: '🎓',
    color: 'blue',
    wordCount: 55,
  },
  {
    id: 'family',
    name: 'Gia đình',
    nameVi: 'Gia đình',
    enName: 'Family',
    nameEn: 'Family',
    title: 'Family (Gia đình)',
    introText: 'Chủ đề về gia đình gồm 40 từ vựng là:',
    icon: '👨‍👩‍👧‍👦',
    color: 'rose',
    wordCount: 40,
  },
  {
    id: 'fruits',
    name: 'Trái cây',
    nameVi: 'Trái cây',
    enName: 'Fruits',
    nameEn: 'Fruits',
    title: 'Fruits (Trái cây)',
    introText: 'Khám phá ngay 39 từ vựng cơ bản liên quan đến chủ đề trái cây.',
    icon: '🍎',
    color: 'red',
    wordCount: 39,
  },
  {
    id: 'animals',
    name: 'Động vật',
    nameVi: 'Động vật',
    enName: 'Animal',
    nameEn: 'Animal',
    title: 'Animal (Động vật)',
    introText: 'Bao gồm: 40 từ vựng cơ bản về động vật, bạn có thể tham khảo tại đây.',
    icon: '🦁',
    color: 'amber',
    wordCount: 40,
  },
  {
    id: 'insects',
    name: 'Côn trùng',
    nameVi: 'Côn trùng',
    enName: 'Insect',
    nameEn: 'Insect',
    title: 'Insect (Côn trùng)',
    introText: 'Chủ đề về côn trùng cũng vô cùng đa dạng với 18 từ vựng cơ bản.',
    icon: '🐞',
    color: 'emerald',
    wordCount: 18,
  },
  {
    id: 'study',
    name: 'Học tập',
    nameVi: 'Học tập',
    enName: 'Study',
    nameEn: 'Study',
    title: 'Study (Học tập)',
    introText: 'Có 40 từ vựng thuộc chủ đề học tập.',
    icon: '📖',
    color: 'teal',
    wordCount: 40,
  },
  {
    id: 'plants',
    name: 'Thực vật',
    nameVi: 'Thực vật',
    enName: 'Plants',
    nameEn: 'Plants',
    title: 'Plants (Thực vật)',
    introText: 'Tìm hiểu 17 từ vựng cơ bản về chủ đề các loài thực vật.',
    icon: '🌲',
    color: 'green',
    wordCount: 17,
  },
  {
    id: 'countries',
    name: 'Quốc gia',
    nameVi: 'Quốc gia',
    enName: 'Country',
    nameEn: 'Country',
    title: 'Country (Quốc gia)',
    introText: 'Chủ đề quốc gia gồm 15 từ vựng là:',
    icon: '🌍',
    color: 'blue',
    wordCount: 15,
  },
  {
    id: 'seafood',
    name: 'Hải sản',
    nameVi: 'Hải sản',
    enName: 'Seafood',
    nameEn: 'Seafood',
    title: 'Seafood (Hải sản)',
    introText: 'Có 17 từ vựng cơ bản về chủ đề hải sản.',
    icon: '🦐',
    color: 'cyan',
    wordCount: 17,
  },
  {
    id: 'energy',
    name: 'Năng lượng',
    nameVi: 'Năng lượng',
    enName: 'Energy',
    nameEn: 'Energy',
    title: 'Energy (Năng lượng)',
    introText: 'Dưới đây là 17 từ vựng cơ bản về đề tài năng lượng.',
    icon: '⚡',
    color: 'yellow',
    wordCount: 17,
  },
  {
    id: 'jobs',
    name: 'Nghề nghiệp',
    nameVi: 'Nghề nghiệp',
    enName: 'Jobs',
    nameEn: 'Jobs',
    title: 'Jobs (Nghề nghiệp)',
    introText: 'Có 40 từ vựng cơ bản về chủ đề nghề nghiệp.',
    icon: '💼',
    color: 'slate',
    wordCount: 40,
  },
  {
    id: 'diet',
    name: 'Chế độ ăn',
    nameVi: 'Chế độ ăn',
    enName: 'Diet',
    nameEn: 'Diet',
    title: 'Diet (Chế độ ăn)',
    introText: 'Có 19 từ vựng cơ bản về chủ đề chế độ ăn uống.',
    icon: '🥗',
    color: 'emerald',
    wordCount: 19,
  },
  {
    id: 'natural_disasters',
    name: 'Thảm họa thiên nhiên',
    nameVi: 'Thảm họa thiên nhiên',
    enName: 'Natural disaster',
    nameEn: 'Natural disaster',
    title: 'Natural disaster (Thảm họa thiên nhiên)',
    introText: 'Chủ đề thảm họa thiên nhiên gồm 15 từ vựng cơ bản.',
    icon: '🌋',
    color: 'red',
    wordCount: 15,
  },
  {
    id: 'asking_way',
    name: 'Chỉ đường',
    nameVi: 'Chỉ đường',
    enName: 'Asking the way',
    nameEn: 'Asking the way',
    title: 'Asking the way (Chỉ đường)',
    introText: 'Có 17 từ vựng cơ bản về chỉ đường.',
    icon: '🗺️',
    color: 'indigo',
    wordCount: 17,
  },
  {
    id: 'hotel_room',
    name: 'Phòng khách sạn',
    nameVi: 'Phòng khách sạn',
    enName: 'A hotel room',
    nameEn: 'A hotel room',
    title: 'A hotel room (Phòng khách sạn)',
    introText: 'Có 19 từ vựng cơ bản về chủ đề phòng khách sạn.',
    icon: '🛎️',
    color: 'amber',
    wordCount: 19,
  },
  {
    id: 'post_office',
    name: 'Ở bưu điện',
    nameVi: 'Ở bưu điện',
    enName: 'At the post office',
    nameEn: 'At the post office',
    title: 'At the post office (Ở bưu điện)',
    introText: 'Có 24 từ vựng cơ bản về chủ đề ở bưu điện.',
    icon: '📮',
    color: 'blue',
    wordCount: 24,
  },
  {
    id: 'bank',
    name: 'Ngân hàng',
    nameVi: 'Ngân hàng',
    enName: 'At the bank',
    nameEn: 'At the bank',
    title: 'At the bank (Ngân hàng)',
    introText: 'Có 100 từ vựng thuộc chuyên ngành ngân hàng.',
    icon: '🏦',
    color: 'emerald',
    wordCount: 100,
  },
];

export const DIFFICULTY_LEVELS = [
  { id: 'ALL', name: 'Tất cả cấp độ', label: 'Tất cả', color: 'slate', badge: 'All', desc: 'Toàn bộ từ vựng theo chủ đề' },
  { id: 'A1', name: 'A1 - Căn bản (Beginner)', label: 'A1', color: 'emerald', badge: 'A1', desc: 'Từ vựng thông dụng cơ bản nhất theo Oxford 3000' },
  { id: 'A2', name: 'A2 - Sơ cấp (Elementary)', label: 'A2', color: 'sky', badge: 'A2', desc: 'Từ vựng giao tiếp & tình huống thực tế' },
  { id: 'B1', name: 'B1 - Trung cấp (Intermediate)', label: 'B1', color: 'amber', badge: 'B1', desc: 'Từ vựng thảo luận, học tập & công sở' },
  { id: 'B2', name: 'B2 - Trung cao cấp (Upper Int.)', label: 'B2', color: 'purple', badge: 'B2', desc: 'Từ vựng học thuật, chuyên ngành & nâng cao' },
];
