// Generator script to produce full 60 topics vocabulary dataset with Oxford 3000 CEFR levels
const fs = require('fs');
const path = require('path');

const TOPICS = [
  { id: 'school_supplies', name: 'Đồ dùng học tập', enName: 'School Supplies', icon: '🎒', color: 'indigo' },
  { id: 'actions', name: 'Hành động', enName: 'Actions', icon: '🏃', color: 'emerald' },
  { id: 'everyday_activities', name: 'Hoạt động thường ngày', enName: 'Everyday Activities', icon: '☕', color: 'amber' },
  { id: 'sea', name: 'Biển & Đại dương', enName: 'Sea & Ocean', icon: '🌊', color: 'cyan' },
  { id: 'numbers', name: 'Số đếm & Toán học', enName: 'Numbers & Math', icon: '🔢', color: 'blue' },
  { id: 'shopping', name: 'Mua sắm', enName: 'Shopping', icon: '🛍️', color: 'pink' },
  { id: 'bedroom', name: 'Phòng ngủ', enName: 'Bedroom', icon: '🛏️', color: 'purple' },
  { id: 'friendship', name: 'Tình bạn', enName: 'Friendship', icon: '🤝', color: 'rose' },
  { id: 'kitchen', name: 'Vật dụng nhà bếp', enName: 'Kitchen Utensils', icon: '🍳', color: 'orange' },
  { id: 'jewelry', name: 'Đồ trang sức', enName: 'Jewelry & Accessories', icon: '💍', color: 'yellow' },
  { id: 'environment', name: 'Môi trường', enName: 'Environment', icon: '🌱', color: 'emerald' },
  { id: 'living_room', name: 'Phòng khách', enName: 'Living Room', icon: '🛋️', color: 'teal' },
  { id: 'hospital', name: 'Bệnh viện & Y tế', enName: 'Hospital & Healthcare', icon: '🏥', color: 'red' },
  { id: 'computer', name: 'Máy tính & Công nghệ', enName: 'Computer & Tech', icon: '💻', color: 'sky' },
  { id: 'housework', name: 'Công việc nhà', enName: 'Housework', icon: '🧹', color: 'amber' },
  { id: 'shops', name: 'Các cửa hàng', enName: 'Stores & Shops', icon: '🏪', color: 'indigo' },
  { id: 'entertainment', name: 'Giải trí', enName: 'Entertainment', icon: '🎭', color: 'purple' },
  { id: 'traveling', name: 'Du lịch & Khám phá', enName: 'Traveling & Vacation', icon: '✈️', color: 'blue' },
  { id: 'hometown', name: 'Quê hương & Thiên nhiên', enName: 'Hometown & Nature', icon: '🏡', color: 'green' },
  { id: 'mid_autumn', name: 'Tết Trung thu', enName: 'Mid-Autumn Festival', icon: '🥮', color: 'yellow' },
  { id: 'wedding', name: 'Đám cưới & Hôn nhân', enName: 'Wedding & Marriage', icon: '💒', color: 'rose' },
  { id: 'airport', name: 'Sân bay & Hàng không', enName: 'Airport & Aviation', icon: '🛫', color: 'sky' },
  { id: 'health', name: 'Sức khỏe & Bệnh tật', enName: 'Health & Illness', icon: '🩺', color: 'red' },
  { id: 'vegetables', name: 'Rau củ quả', enName: 'Vegetables & Herbs', icon: '🥦', color: 'green' },
  { id: 'transport', name: 'Phương tiện giao thông', enName: 'Transport & Traffic', icon: '🚗', color: 'orange' },
  { id: 'time', name: 'Thời gian & Niên đại', enName: 'Time & Chronology', icon: '🗓️', color: 'sky' },
  { id: 'emotions', name: 'Cảm xúc & Tâm trạng', enName: 'Emotions & Moods', icon: '😊', color: 'pink' },
  { id: 'character', name: 'Tính cách & Phẩm chất', enName: 'Personality & Character', icon: '🧠', color: 'indigo' },
  { id: 'drinks', name: 'Đồ uống & Thức uống', enName: 'Drinks & Beverages', icon: '🍹', color: 'amber' },
  { id: 'flowers', name: 'Các loài hoa', enName: 'Flowers & Blooms', icon: '🌸', color: 'rose' },
  { id: 'movies', name: 'Điện ảnh & Phim ảnh', enName: 'Movies & Cinema', icon: '🎬', color: 'purple' },
  { id: 'soccer', name: 'Bóng đá & Thể thao vua', enName: 'Soccer & Football', icon: '⚽', color: 'emerald' },
  { id: 'christmas', name: 'Giáng sinh', enName: 'Christmas & Winter', icon: '🎄', color: 'red' },
  { id: 'foods', name: 'Ẩm thực & Đồ ăn', enName: 'Foods & Culinary', icon: '🍲', color: 'orange' },
  { id: 'sports', name: 'Thể thao & Vận động', enName: 'Sports & Games', icon: '🏆', color: 'blue' },
  { id: 'music', name: 'Âm nhạc & Nhạc cụ', enName: 'Music & Instruments', icon: '🎵', color: 'violet' },
  { id: 'love', name: 'Tình yêu & Hẹn hò', enName: 'Love & Romance', icon: '💖', color: 'pink' },
  { id: 'restaurant_hotel', name: 'Nhà hàng & Khách sạn', enName: 'Restaurant & Hotel', icon: '🍽️', color: 'amber' },
  { id: 'school', name: 'Trường học & Giáo dục', enName: 'School & Campus', icon: '🏫', color: 'cyan' },
  { id: 'colors', name: 'Màu sắc', enName: 'Colors & Hues', icon: '🎨', color: 'indigo' },
  { id: 'weather', name: 'Thời tiết & Khí hậu', enName: 'Weather & Climate', icon: '☀️', color: 'yellow' },
  { id: 'clothes', name: 'Quần áo & Thời trang', enName: 'Clothes & Fashion', icon: '👗', color: 'pink' },
  { id: 'body_parts', name: 'Bộ phận cơ thể', enName: 'Body Parts', icon: '🧍', color: 'orange' },
  { id: 'education', name: 'Giáo dục & Đại học', enName: 'Higher Education', icon: '🎓', color: 'blue' },
  { id: 'family', name: 'Gia đình & Dòng họ', enName: 'Family & Relatives', icon: '👨‍👩‍👧‍👦', color: 'rose' },
  { id: 'fruits', name: 'Trái cây & Hoa quả', enName: 'Fruits & Berries', icon: '🍎', color: 'red' },
  { id: 'animals', name: 'Động vật thế giới', enName: 'Animals & Wildlife', icon: '🦁', color: 'amber' },
  { id: 'insects', name: 'Côn trùng', enName: 'Insects & Bugs', icon: '🐞', color: 'emerald' },
  { id: 'study', name: 'Học tập & Nghiên cứu', enName: 'Study & Tools', icon: '📖', color: 'teal' },
  { id: 'plants', name: 'Thực vật & Cây cối', enName: 'Plants & Trees', icon: '🌲', color: 'green' },
  { id: 'countries', name: 'Quốc gia & Thế giới', enName: 'Countries & Nations', icon: '🌍', color: 'blue' },
  { id: 'seafood', name: 'Hải sản', enName: 'Seafood & Marine', icon: '🦐', color: 'cyan' },
  { id: 'energy', name: 'Năng lượng & Công nghiệp', enName: 'Energy & Power', icon: '⚡', color: 'yellow' },
  { id: 'jobs', name: 'Nghề nghiệp & Việc làm', enName: 'Jobs & Professions', icon: '💼', color: 'slate' },
  { id: 'diet', name: 'Chế độ ăn & Dinh dưỡng', enName: 'Diet & Nutrition', icon: '🥗', color: 'emerald' },
  { id: 'natural_disasters', name: 'Thảm họa thiên nhiên', enName: 'Natural Disasters', icon: '🌋', color: 'red' },
  { id: 'asking_way', name: 'Chỉ đường & Giao thông', enName: 'Asking the Way', icon: '🗺️', color: 'indigo' },
  { id: 'hotel_room', name: 'Phòng khách sạn & Dịch vụ', enName: 'Hotel Room Services', icon: '🛎️', color: 'amber' },
  { id: 'post_office', name: 'Bưu điện & Thư tín', enName: 'Post Office & Mail', icon: '📮', color: 'blue' },
  { id: 'bank', name: 'Tài chính & Ngân hàng', enName: 'Banking & Finance', icon: '🏦', color: 'emerald' },
];

console.log('Total topics count:', TOPICS.length);
