const fs = require('fs');
const path = require('path');

const TOPICS = [
  { id: 'school_supplies', name: 'Đồ dùng học tập', enName: 'School Supplies', icon: '🎒', color: 'indigo' },
  { id: 'actions', name: 'Hành động', enName: 'Actions', icon: '🏃', color: 'emerald' },
  { id: 'everyday_activities', name: 'Hoạt động thường ngày', enName: 'Everyday Activities', icon: '☕', color: 'amber' },
  { id: 'sea', name: 'Biển & Đại dương', enName: 'Sea & Ocean', icon: '🌊', color: 'cyan' },
  { id: 'numbers', name: 'Số đếm & Toán học', enName: 'Numbers & Math', icon: '🔢', color: 'blue' },
  { id: 'shopping', name: 'Mua sắm', enName: 'Shopping', icon: '🛍️', color: 'pink' },
  { id: 'bedroom', name: 'Phòng ngủ', enName: 'Bedroom', icon: '🛏️', color: 'purple' },
  { id: 'friendship', name: 'Tình bạn', enName: 'Friendship', icon: '🤝', color: 'rose' },
  { id: 'kitchen', name: 'Vật dụng nhà bếp', enName: 'Kitchen Utensils', icon: '🍳', color: 'orange' },
  { id: 'jewelry', name: 'Đồ trang sức', enName: 'Jewelry & Accessories', icon: '💍', color: 'yellow' },
  { id: 'environment', name: 'Môi trường', enName: 'Environment', icon: '🌱', color: 'emerald' },
  { id: 'living_room', name: 'Phòng khách', enName: 'Living Room', icon: '🛋️', color: 'teal' },
  { id: 'hospital', name: 'Bệnh viện & Y tế', enName: 'Hospital & Healthcare', icon: '🏥', color: 'red' },
  { id: 'computer', name: 'Máy tính & Công nghệ', enName: 'Computer & Tech', icon: '💻', color: 'sky' },
  { id: 'housework', name: 'Công việc nhà', enName: 'Housework', icon: '🧹', color: 'amber' },
  { id: 'shops', name: 'Các cửa hàng', enName: 'Stores & Shops', icon: '🏪', color: 'indigo' },
  { id: 'entertainment', name: 'Giải trí', enName: 'Entertainment', icon: '🎭', color: 'purple' },
  { id: 'traveling', name: 'Du lịch & Khám phá', enName: 'Traveling & Vacation', icon: '✈️', color: 'blue' },
  { id: 'hometown', name: 'Quê hương & Thiên nhiên', enName: 'Hometown & Nature', icon: '🏡', color: 'green' },
  { id: 'mid_autumn', name: 'Tết Trung thu', enName: 'Mid-Autumn Festival', icon: '🥮', color: 'yellow' },
  { id: 'wedding', name: 'Đám cưới & Hôn nhân', enName: 'Wedding & Marriage', icon: '💒', color: 'rose' },
  { id: 'airport', name: 'Sân bay & Hàng không', enName: 'Airport & Aviation', icon: '🛫', color: 'sky' },
  { id: 'health', name: 'Sức khỏe & Bệnh tật', enName: 'Health & Illness', icon: '🩺', color: 'red' },
  { id: 'vegetables', name: 'Rau củ quả', enName: 'Vegetables & Herbs', icon: '🥦', color: 'green' },
  { id: 'transport', name: 'Phương tiện giao thông', enName: 'Transport & Traffic', icon: '🚗', color: 'orange' },
  { id: 'time', name: 'Thời gian & Niên đại', enName: 'Time & Chronology', icon: '⏰', color: 'violet' },
  { id: 'emotions', name: 'Cảm xúc & Tâm trạng', enName: 'Emotions & Moods', icon: '😊', color: 'pink' },
  { id: 'character', name: 'Tính cách & Phẩm chất', enName: 'Personality & Character', icon: '🧠', color: 'indigo' },
  { id: 'drinks', name: 'Đồ uống & Thức uống', enName: 'Drinks & Beverages', icon: '🍹', color: 'amber' },
  { id: 'flowers', name: 'Các loài hoa', enName: 'Flowers & Blooms', icon: '🌸', color: 'rose' },
  { id: 'movies', name: 'Điện ảnh & Phim ảnh', enName: 'Movies & Cinema', icon: '🎬', color: 'purple' },
  { id: 'soccer', name: 'Bóng đá & Thể thao vua', enName: 'Soccer & Football', icon: '⚽', color: 'emerald' },
  { id: 'christmas', name: 'Giáng sinh', enName: 'Christmas & Winter', icon: '🎄', color: 'red' },
  { id: 'foods', name: 'Ẩm thực & Đồ ăn', enName: 'Foods & Culinary', icon: '🍲', color: 'orange' },
  { id: 'sports', name: 'Thể thao & Vận động', enName: 'Sports & Games', icon: '🏆', color: 'blue' },
  { id: 'music', name: 'Âm nhạc & Nhạc cụ', enName: 'Music & Instruments', icon: '🎵', color: 'violet' },
  { id: 'love', name: 'Tình yêu & Hẹn hò', enName: 'Love & Romance', icon: '💖', color: 'pink' },
  { id: 'restaurant_hotel', name: 'Nhà hàng & Khách sạn', enName: 'Restaurant & Hotel', icon: '🍽️', color: 'amber' },
  { id: 'school', name: 'Trường học & Giáo dục', enName: 'School & Campus', icon: '🏫', color: 'cyan' },
  { id: 'colors', name: 'Màu sắc', enName: 'Colors & Hues', icon: '🎨', color: 'indigo' },
  { id: 'weather', name: 'Thời tiết & Khí hậu', enName: 'Weather & Climate', icon: '☀️', color: 'yellow' },
  { id: 'clothes', name: 'Quần áo & Thời trang', enName: 'Clothes & Fashion', icon: '👗', color: 'pink' },
  { id: 'body_parts', name: 'Bộ phận cơ thể', enName: 'Body Parts', icon: '🧍', color: 'orange' },
  { id: 'education', name: 'Giáo dục & Đại học', enName: 'Higher Education', icon: '🎓', color: 'blue' },
  { id: 'family', name: 'Gia đình & Dòng họ', enName: 'Family & Relatives', icon: '👨‍👩‍👧‍👦', color: 'rose' },
  { id: 'fruits', name: 'Trái cây & Hoa quả', enName: 'Fruits & Berries', icon: '🍎', color: 'red' },
  { id: 'animals', name: 'Động vật thế giới', enName: 'Animals & Wildlife', icon: '🦁', color: 'amber' },
  { id: 'insects', name: 'Côn trùng', enName: 'Insects & Bugs', icon: '🐞', color: 'emerald' },
  { id: 'study', name: 'Học tập & Nghiên cứu', enName: 'Study & Tools', icon: '📖', color: 'teal' },
  { id: 'plants', name: 'Thực vật & Cây cối', enName: 'Plants & Trees', icon: '🌲', color: 'green' },
  { id: 'countries', name: 'Quốc gia & Thế giới', enName: 'Countries & Nations', icon: '🌍', color: 'blue' },
  { id: 'seafood', name: 'Hải sản', enName: 'Seafood & Marine', icon: '🦐', color: 'cyan' },
  { id: 'energy', name: 'Năng lượng & Công nghiệp', enName: 'Energy & Power', icon: '⚡', color: 'yellow' },
  { id: 'jobs', name: 'Nghề nghiệp & Việc làm', enName: 'Jobs & Professions', icon: '💼', color: 'slate' },
  { id: 'diet', name: 'Chế độ ăn & Dinh dưỡng', enName: 'Diet & Nutrition', icon: '🥗', color: 'emerald' },
  { id: 'natural_disasters', name: 'Thảm họa thiên nhiên', enName: 'Natural Disasters', icon: '🌋', color: 'red' },
  { id: 'asking_way', name: 'Chỉ đường & Giao thông', enName: 'Asking the Way', icon: '🗺️', color: 'indigo' },
  { id: 'hotel_room', name: 'Phòng khách sạn & Dịch vụ', enName: 'Hotel Room Services', icon: '🛎️', color: 'amber' },
  { id: 'post_office', name: 'Bưu điện & Thư tín', enName: 'Post Office & Mail', icon: '📮', color: 'blue' },
  { id: 'bank', name: 'Tài chính & Ngân hàng', enName: 'Banking & Finance', icon: '🏦', color: 'emerald' },
];

const RAW_TOPIC_DATA = {
  environment: [
    ['land', '/lænd/', 'đất, đất đai', 'A1', 'n.', 'Fertile land is vital for growing organic crops.', 'Đất màu mỡ rất quan trọng để trồng nông sản hữu cơ.'],
    ['pollute', '/pəˈluːt/', 'gây ô nhiễm', 'B1', 'v.', 'Plastic waste continues to pollute the oceans.', 'Rác thải nhựa tiếp tục gây ô nhiễm các đại dương.'],
    ['decompose', '/ˌdiː.kəmˈpəʊz/', 'thối rữa, phân hủy sinh học', 'B2', 'v.', 'Organic food waste decomposes into natural fertilizer.', 'Rác thải hữu cơ phân hủy thành phân bón tự nhiên.'],
    ['balance', '/ˈbæl.əns/', '(trạng thái) cân bằng sinh thái', 'B1', 'n.', 'Preserving the balance of nature is crucial.', 'Duy trì sự cân bằng tự nhiên là điều tối quan trọng.'],
    ['climate change', '/ˈklaɪ.mət ˌtʃeɪndʒ/', 'biến đổi khí hậu', 'B1', 'n.', 'Global actions are needed to mitigate climate change.', 'Cần có hành động toàn cầu để giảm thiểu biến đổi khí hậu.'],
    ['global warming', '/ˌɡləʊ.bəl ˈwɔː.mɪŋ/', 'hiện tượng ấm lên toàn cầu', 'B1', 'n.', 'Global warming causes polar ice caps to melt.', 'Sự ấm lên toàn cầu khiến băng ở hai cực tan chảy.'],
    ['oil slick', '/ˈɔɪl ˌslɪk/', 'vệt dầu loang trên biển', 'B2', 'n.', 'The oil slick threatened marine wildlife along the shore.', 'Vệt dầu loang đe dọa sinh vật biển dọc bờ biển.'],
    ['ozone layer', '/ˈəʊ.zəʊn ˌleɪ.ər/', 'tầng ozon bảo vệ', 'B2', 'n.', 'The ozone layer shields Earth from harmful UV rays.', 'Tầng ozon bảo vệ Trái Đất khỏi tia cực tím có hại.'],
    ['biodiversity', '/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/', 'đa dạng sinh học', 'B2', 'n.', 'Tropical rainforests boast immense biodiversity.', 'Rừng nhiệt đới sở hữu sự đa dạng sinh học vô cùng phong phú.'],
    ['ecology', '/iˈkɒl.ə.dʒi/', 'hệ sinh thái, sinh thái học', 'B2', 'n.', 'Human activities have a profound impact on ecology.', 'Hoạt động của con người có tác động sâu sắc đến hệ sinh thái.'],
    ['water', '/ˈwɔː.tər/', 'nước', 'A1', 'n.', 'Clean drinking water is essential for all life.', 'Nước uống sạch là thiết yếu đối với mọi sự sống.'],
    ['air', '/eər/', 'không khí', 'A1', 'n.', 'Planting more trees purifies the city air.', 'Trồng thêm cây xanh giúp làm sạch không khí thành phố.'],
    ['forest', '/ˈfɒr.ɪst/', 'rừng, khu rừng', 'A2', 'n.', 'The national park protects a lush primeval forest.', 'Vườn quốc gia bảo vệ một khu rừng nguyên sinh tươi tốt.'],
    ['flora', '/ˈflɔː.rə/', 'hệ thực vật', 'B2', 'n.', 'The mountain is home to hundreds of rare flora species.', 'Ngọn núi là nơi cư ngụ của hàng trăm loài thực vật quý hiếm.'],
    ['creature', '/ˈkriː.tʃər/', 'sinh vật sống', 'B2', 'n.', 'Deep sea creatures have adapted to pitch darkness.', 'Các sinh vật biển sâu đã thích nghi với bóng tối mịt mù.'],
    ['insect', '/ˈɪn.sekt/', 'loài côn trùng', 'A2', 'n.', 'Bees are vital pollinating insects for crops.', 'Ong là loài côn trùng thụ phấn thiết yếu cho cây trồng.'],
    ['reproduction', '/ˌriː.prəˈdʌk.ʃən/', 'quá trình sinh sản', 'B2', 'n.', 'Spring is the season of animal reproduction.', 'Mùa xuân là mùa sinh sản của các loài động vật.'],
    ['wildlife', '/ˈwaɪld.laɪf/', 'động vật hoang dã', 'B2', 'n.', 'Protecting natural habitats saves endangered wildlife.', 'Bảo vệ môi trường sống tự nhiên cứu động vật hoang dã nguy cấp.'],
    ['sewage', '/ˈsuː.ɪdʒ/', 'nước thải sinh hoạt/công nghiệp', 'B2', 'n.', 'Modern cities treat sewage before returning water to rivers.', 'Các thành phố hiện đại xử lý nước thải trước khi trả lại cho sông suối.'],
    ['fauna', '/ˈfɔː.nə/', 'hệ động vật', 'B2', 'n.', 'Australia is renowned for its unique native fauna.', 'Nước Úc nổi tiếng với hệ động vật bản địa độc đáo.']
  ],
  living_room: [
    ['drapes', '/dreɪps/', 'màn cửa sổ sang trọng', 'B2', 'n.', 'Velvet drapes frame the tall living room windows.', 'Rèm nhung đóng khung cửa sổ phòng khách cao vút.'],
    ['cushion', '/ˈkʊʃ.ən/', 'đệm ngồi, gối trang trí sofa', 'B1', 'n.', 'Colorful cushions make the couch extra cozy.', 'Những chiếc gối ôm nhiều màu làm chiếc sofa thêm ấm cúng.'],
    ['sofa', '/ˈsəʊ.fə/', 'ghế sô-pha, ghế dài', 'A1', 'n.', 'We sat on the comfortable leather sofa to chat.', 'Chúng tôi ngồi trên chiếc sofa da êm ái để trò chuyện.'],
    ['rug', '/rʌɡ/', 'tấm thảm trải sàn', 'A2', 'n.', 'A Persian rug adds warmth to the wooden floor.', 'Chiếc thảm Ba Tư mang lại sự ấm áp cho sàn gỗ.'],
    ['banister', '/ˈbæn.ɪ.stər/', 'thành tay vịn cầu thang', 'B2', 'n.', 'Hold onto the wooden banister while walking downstairs.', 'Hãy vịn vào tay vịn cầu thang gỗ khi đi xuống.'],
    ['bookcase', '/ˈbʊk.keɪs/', 'tủ sách phòng khách', 'A2', 'n.', 'The wooden bookcase is filled with English literature.', 'Tủ sách bằng gỗ chất đầy các tác phẩm văn học tiếng Anh.'],
    ['ceiling', '/ˈsiː.lɪŋ/', 'trần nhà', 'B1', 'n.', 'The living room features high ceilings with recessed lights.', 'Phòng khách có trần nhà cao với hệ thống đèn âm trần.'],
    ['clock', '/klɒk/', 'đồng hồ treo tường', 'A1', 'n.', 'The grandfather clock chimed every hour on the dot.', 'Chiếc đồng hồ quả lắc điểm chuông đúng từng giờ.'],
    ['desk', '/desk/', 'bàn làm việc phòng khách', 'A1', 'n.', 'A compact writing desk sits neatly in the corner.', 'Một chiếc bàn viết nhỏ gọn nằm ngay ngắn ở góc phòng.'],
    ['frame', '/freɪm/', 'khung ảnh, khung tranh', 'B1', 'n.', 'Family photos are displayed in polished wooden frames.', 'Ảnh gia đình được trưng bày trong những khung gỗ bóng loáng.'],
    ['lampshade', '/ˈlæmp.ʃeɪd/', 'cái chụp đèn trang trí', 'B2', 'n.', 'A silk lampshade diffuses warm golden light.', 'Chụp đèn bằng lụa khuếch tán ánh sáng vàng ấm áp.'],
    ['mantelpiece', '/ˈmæn.təl.piːs/', 'bệ lò sưởi', 'B2', 'n.', 'Scented candles are placed upon the stone mantelpiece.', 'Những ngọn nến thơm được đặt trên bệ lò sưởi bằng đá.'],
    ['painting', '/ˈpeɪn.tɪŋ/', 'bức tranh nghệ thuật', 'A1', 'n.', 'An abstract oil painting hangs above the sofa.', 'Một bức tranh sơn dầu trừu tượng treo phía trên ghế sofa.'],
    ['remote control', '/rɪˌməʊt kənˈtrəʊl/', 'thiết bị điều khiển từ xa', 'A2', 'n.', 'Use the remote control to adjust television volume.', 'Dùng điều khiển từ xa để chỉnh âm lượng tivi.'],
    ['speaker', '/ˈspiː.kər/', 'loa âm thanh', 'A2', 'n.', 'Bluetooth speakers stream crisp acoustic music.', 'Loa bluetooth phát nhạc acoustic trong trẻo.'],
    ['step', '/step/', 'bậc cầu thang', 'A2', 'n.', 'Walk up the carpeted steps carefully.', 'Bước lên các bậc thang trải thảm cẩn thận.'],
    ['stereo system', '/ˈster.i.əʊ ˈsɪs.təm/', 'dàn máy hát âm thanh', 'B1', 'n.', 'The modern stereo system provides rich surround sound.', 'Dàn âm thanh hiện đại mang lại hiệu ứng vòm sống động.'],
    ['stereo', '/ˈster.i.əʊ/', 'máy nghe nhạc xtê-rê-ô', 'A2', 'n.', 'He plugged his headphones into the vintage stereo.', 'Anh cắm tai nghe vào chiếc máy phát nhạc cổ điển.'],
    ['television', '/ˈtel.ɪ.vɪʒ.ən/', 'vô tuyến, TV', 'A1', 'n.', 'The family gathers in the evening to watch television.', 'Cả gia đình quây quần vào buổi tối để xem tivi.'],
    ['vase', '/vɑːz/', 'bình hoa, lọ hoa trang trí', 'A2', 'n.', 'A ceramic vase filled with fresh lilies brightens the room.', 'Bình gốm cắm đầy hoa ly tươi thắm làm bừng sáng căn phòng.'],
    ['wall unit', '/wɔːl ˈjuː.nɪt/', 'tủ kệ tường', 'B1', 'n.', 'The minimalist wall unit holds the TV and game console.', 'Kệ tủ tường tối giản chứa tivi và máy chơi game.'],
    ['lamp', '/læmp/', 'đèn phòng', 'A2', 'n.', 'A stylish floor lamp illuminates the reading nook.', 'Cây đèn đứng phong cách soi sáng góc đọc sách.'],
    ['calendar', '/ˈkæl.ən.dər/', 'tấm lịch treo tường', 'A2', 'n.', 'Mark your study schedule on the yearly calendar.', 'Đánh dấu lịch học của bạn trên tờ lịch năm.'],
    ['fan', '/fæn/', 'cái quạt mát', 'A2', 'n.', 'The ceiling fan circulates cool air during summer days.', 'Quạt trần lưu thông gió mát trong những ngày hè.'],
    ['chair', '/tʃeər/', 'cái ghế bành', 'A1', 'n.', 'Relax in the comfortable leather armchair.', 'Thư giãn trên chiếc ghế bành bọc da êm ái.'],
    ['stool', '/stuːl/', 'ghế đẩu không tựa', 'B2', 'n.', 'Wooden footstools can double as small side tables.', 'Những chiếc ghế đẩu bằng gỗ có thể dùng làm bàn nhỏ bên cạnh.'],
    ['ashtray', '/ˈæʃ.treɪ/', 'gạt tàn thuốc', 'B2', 'n.', 'A crystal ashtray sat on the terrace coffee table.', 'Một chiếc gạt tàn pha lê đặt trên bàn cà phê ngoài ban công.'],
    ['bookshelf', '/ˈbʊk.ʃelf/', 'kệ sách treo tường', 'A2', 'n.', 'Her favorite English novels are lined up on the bookshelf.', 'Những cuốn tiểu thuyết tiếng Anh yêu thích xếp ngay ngắn trên kệ.'],
    ['fuse', '/fjuːz/', 'cầu chì an toàn', 'B2', 'n.', 'The electrical fuse prevents power surges in the house.', 'Cầu chì điện ngăn ngừa sự cố chập quá tải trong nhà.'],
    ['switch', '/swɪtʃ/', 'công tắc điện', 'B1', 'n.', 'Flip the wall switch to illuminate the living space.', 'Bật công tắc tường để chiếu sáng không gian sinh hoạt.'],
    ['couch', '/kaʊtʃ/', 'ghế sa lông, đi-văng', 'A2', 'n.', 'We stretched out on the plush couch to watch movies.', 'Chúng tôi ngả lưng trên chiếc ghế đi-văng êm ái xem phim.'],
    ['curtain', '/ˈkɜː.tən/', 'rèm che cửa sổ', 'B1', 'n.', 'She parted the curtains to enjoy the morning garden view.', 'Cô ấy vén rèm để ngắm nhìn khu vườn buổi sớm.']
  ],
  hospital: [
    ['radiologist', '/ˌreɪ.diˈɒl.ə.dʒɪst/', 'bác sĩ chụp X-quang, chẩn đoán hình ảnh', 'B2', 'n.', 'The radiologist examined the MRI scan closely.', 'Bác sĩ chẩn đoán hình ảnh đã kiểm tra kỹ bản chụp cộng hưởng từ.'],
    ['emergency room', '/ɪˈmɜː.dʒən.si ˌruːm/', 'phòng cấp cứu', 'B1', 'n.', 'The ambulance rushed directly to the emergency room.', 'Xe cứu thương lao thẳng đến khu vực phòng cấp cứu.'],
    ['obstetrician', '/ˌɒb.stəˈtrɪʃ.ən/', 'bác sĩ sản khoa', 'B2', 'n.', 'The obstetrician monitored the baby health throughout delivery.', 'Bác sĩ sản khoa theo dõi sát sức khỏe thai nhi trong suốt ca sinh.'],
    ['operating room', '/ˈɒp.ər.eɪ.tɪŋ ˌruːm/', 'phòng phẫu thuật, phòng mổ', 'B1', 'n.', 'Surgeons scrubbed thoroughly before entering the operating room.', 'Các bác sĩ phẫu thuật rửa tay khử trùng kỹ trước khi vào phòng mổ.'],
    ['needle', '/ˈniː.dəl/', 'kim tiêm y tế', 'B1', 'n.', 'The nurse used a sterilized needle for blood tests.', 'Y tá đã sử dụng kim tiêm vô trùng để lấy mẫu xét nghiệm máu.'],
    ['laboratory', '/ləˈbɒr.ə.tər.i/', 'phòng xét nghiệm, phòng thí nghiệm', 'B1', 'n.', 'Lab technicians processed viral samples in the laboratory.', 'Kỹ thuật viên xét nghiệm đã xử lý các mẫu virus trong phòng lab.'],
    ['pharmacy', '/ˈfɑː.mə.si/', 'hiệu thuốc, nhà thuốc bệnh viện', 'A2', 'n.', 'Collect prescribed antibiotics at the hospital pharmacy.', 'Nhận thuốc kháng sinh theo đơn tại quầy thuốc bệnh viện.'],
    ['hospital bed', '/ˈhɒs.pɪ.təl bed/', 'giường bệnh nhân', 'A2', 'n.', 'The adjustable hospital bed helps patients rest easily.', 'Chiếc giường bệnh điều chỉnh được giúp bệnh nhân nằm nghỉ thoải mái.'],
    ['call button', '/kɔːl ˈbʌt.ən/', 'chuông gọi y tá tại giường', 'B1', 'n.', 'Press the call button if you need nurse assistance.', 'Hãy nhấn chuông gọi nếu bạn cần y tá hỗ trợ.'],
    ['doctor', '/ˈdɒk.tər/', 'bác sĩ điều trị', 'A1', 'n.', 'The doctor provided clear advice on medication dosage.', 'Bác sĩ đã đưa ra lời khuyên rõ ràng về liều lượng dùng thuốc.'],
    ['nurse', '/nɜːs/', 'y tá, điều dưỡng viên', 'A1', 'n.', 'The nurse checked the patient blood pressure every hour.', 'Y tá kiểm tra huyết áp của bệnh nhân sau mỗi giờ.'],
    ['gurney', '/ˈɡɜː.ni/', 'xe cáng, giường đẩy cấp cứu', 'B2', 'n.', 'Paramedics wheeled the patient in on a rolling gurney.', 'Nhân viên cứu thương đẩy bệnh nhân vào trên chiếc xe cáng.'],
    ['waiting room', '/ˈweɪ.tɪŋ ˌruːm/', 'phòng chờ bệnh nhân', 'A2', 'n.', 'Family members waited patiently in the hospital waiting room.', 'Người nhà bệnh nhân kiên nhẫn ngồi đợi ở phòng chờ.'],
    ['surgeon', '/ˈsɜː.dʒən/', 'bác sĩ phẫu thuật chính', 'B2', 'n.', 'The skilled cardiac surgeon performed the bypass flawlessly.', 'Bác sĩ phẫu thuật tim tài ba đã thực hiện ca mổ trọn vẹn.'],
    ['midwife', '/ˈmɪd.waɪf/', 'nữ hộ sinh, bà đỡ', 'B2', 'n.', 'The experienced midwife supported the mother during childbirth.', 'Nữ hộ sinh giàu kinh nghiệm đã hỗ trợ người mẹ vượt cạn.'],
    ['injection', '/ɪnˈdʒek.ʃən/', 'việc tiêm thuốc, mũi tiêm', 'B1', 'n.', 'The flu vaccine injection takes only a few seconds.', 'Mũi tiêm vắc xin cúm chỉ mất vài giây ngắn ngủi.'],
    ['calcium', '/ˈkæl.si.əm/', 'nguyên tố canxi bổ sung', 'B2', 'n.', 'Calcium is essential for building strong teeth and bones.', 'Canxi rất cần thiết để phát triển răng và khung xương chắc khỏe.'],
    ['hospital', '/ˈhɒs.pɪ.təl/', 'bệnh viện, cơ sở y tế', 'A1', 'n.', 'The regional hospital is equipped with modern diagnostic tools.', 'Bệnh viện khu vực được trang bị các thiết bị chẩn đoán hiện đại.'],
    ['crutch', '/krʌtʃ/', 'cái nạng chống đi', 'B2', 'n.', 'He walked with crutches after spraining his left ankle.', 'Anh ấy phải chống nạng sau khi bị bong gân mắt cá chân trái.'],
    ['wheelchair', '/ˈwiːl.tʃeər/', 'xe lăn y tế', 'B1', 'n.', 'Hospitals provide wheelchairs for patients with mobility needs.', 'Bệnh viện cung cấp xe lăn cho các bệnh nhân gặp khó khăn vận động.'],
    ['paramedic', '/ˌpær.əˈmed.ɪk/', 'nhân viên cấp cứu khẩn cấp', 'B2', 'n.', 'Paramedics administered first aid right at the accident scene.', 'Nhân viên cấp cứu đã sơ cứu ngay tại hiện trường vụ việc.'],
    ['stretcher', '/ˈstretʃ.ər/', 'cáng cứu thương', 'B2', 'n.', 'The injured athlete was carried off the field on a stretcher.', 'Vận động viên bị thương được đưa ra khỏi sân bằng cáng cứu thương.'],
    ['rush', '/rʌʃ/', 'đưa đi khẩn cấp, chuyển nhanh', 'B2', 'v.', 'Doctors rushed to stabilize the critical patient.', 'Các bác sĩ gấp rút cấp cứu để ổn định tình trạng bệnh nhân nặng.'],
    ['treat', '/triːt/', 'điều trị, chữa bệnh', 'B1', 'v.', 'Physicians use antibiotics to treat bacterial infections.', 'Bác sĩ sử dụng thuốc kháng sinh để điều trị nhiễm khuẩn.'],
    ['condition', '/kənˈdɪʃ.ən/', 'tình trạng sức khỏe', 'A2', 'n.', 'The patient physical condition is improving steadily.', 'Tình trạng thể chất của bệnh nhân đang cải thiện đều đặn.'],
    ['recovery', '/rɪˈkʌv.ər.i/', 'sự bình phục, quá trình hồi phục', 'B2', 'n.', 'Adequate rest ensures a fast postoperative recovery.', 'Nghỉ ngơi đầy đủ giúp quá trình hồi phục sau phẫu thuật diễn ra nhanh chóng.'],
    ['suffer', '/ˈsʌf.ər/', 'bị bệnh, chịu đựng cơn đau', 'B1', 'v.', 'Many adults suffer from chronic back pain.', 'Nhiều người trưởng thành phải chịu đựng cơn đau lưng mãn tính.'],
    ['deteriorate', '/dɪˈtɪə.ri.ə.reɪt/', 'xấu đi, suy giảm sức khỏe', 'B2', 'v.', 'Seek immediate medical attention if symptoms deteriorate.', 'Hãy đi khám ngay lập tức nếu các triệu chứng có chiều hướng xấu đi.'],
    ['coma', '/ˈkəʊ.mə/', 'tình trạng hôn mê sâu', 'B2', 'n.', 'The patient emerged safely from a week-long coma.', 'Bệnh nhân đã tỉnh lại an toàn sau một tuần hôn mê sâu.'],
    ['common cold', '/ˌkɒm.ən ˈkəʊld/', 'bệnh cảm lạnh thông thường', 'A2', 'n.', 'Drink warm fluids and rest to overcome a common cold.', 'Uống nhiều nước ấm và nghỉ ngơi để vượt qua cơn cảm lạnh thông thường.']
  ]
};

console.log('Building dictionary with base topics...');
